spring.application.name=SpringSecurityDemo

spring.datasource.url=jdbc:postgresql://localhost:5432/abesdb2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=zaid@123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swaggerui.html